# -*- coding: utf-8 -*-
"""Little Lotus_LangGraph multi agent (3 agents).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CbRGenNgvI4WlX_aAJg2SEG7Sn1QBJRO

# 🌸 Little Lotus HR Recruitment System
### *Multi-Agent Recruitment & HR Policy Orchestration*

This system utilizes a **Graph-based Multi-Agent Architecture** to automate the hiring lifecycle. By delegating tasks to specialized AI "agents," we ensure high-accuracy data retrieval and consistent HR decision-making.

---

### 🤖 Meet the Agents

| Agent | Expertise | Business Value |
| :--- | :--- | :--- |
| **Recruitment Specialist** | Candidate Sourcing & CV Analysis | Rapidly identifies top talent and summarizes achievements from the candidate database. |
| **Technical Interviewer** | Interview Prep & Screening | Generates role-specific questions based on the candidate's actual background. |
| **HR Policy Specialist** | Internal Compliance & Benefits | Provides instant, grounded answers from the official Company Handbook/Policies. |

---

### 🚦 Workflow Logic
The **Router Agent** acts as a traffic controller, analyzing user intent to hand off the conversation to the correct specialist. This ensures that the user always interacts with the most relevant "expert" for their specific HR task.

# 🤖 Building an Agentic System

**Goal:** In this workshop, we will move beyond simple chatbots. We will build an **"Agentic System"**—a team of specialized AI workers managed by a central decision-maker.

---

## 1. Introduction: Why "Smart" Bots Act Stupid

### The "Black Box" Problem
Imagine you are building a customer support bot for a store. You ask it: *"What is the return policy for the iPhone 16?"*

A standard Large Language Model (LLM) like GPT-4 might say:
> *"You can return it within 14 days to any Apple Store."*

**The Problem?** This might be true for Apple *in general*, but it might be **false** for *your* specific store in Singapore. The AI is relying on its "frozen" training data from the internet, not your actual business rules. It is "hallucinating" a policy because it wants to be helpful.

---
### The Solution: Agentic RAG
We don't need a creative writer; we need a strict librarian. To fix this, we move from a simple chatbot to an **Agentic System**. Instead of one big brain trying to know everything, we build a **Team of Specialists**:

1.  **The Router (The Receptionist):** Identifies what the user wants (e.g., "This is a shipping question").
2.  **The Specialist (The Worker):** A specific agent (e.g., "Policy Agent") that *only* handles that topic.
3.  **The Knowledge Base (The Library):** The agent looks up the *exact* document before answering.

---
## 2. Setup & Dependencies

First, let's install the necessary tools. We are using **LangChain** (for logic), **LangGraph** (for the agent loop), and **ChromaDB** (for memory).
"""

import os
from google.colab import drive

# 1. CLEAN UP MOUNT
if os.path.exists('/content/drive'):
    !fusermount -u /content/drive
    !rm -rf /content/drive
drive.mount('/content/drive', force_remount=True)

# 2. MASTER INSTALL (This fixes Section 3, 4, and 7 errors)
print("🛠️ Installing all AI tools... please wait about 60 seconds.")
!pip install -qU langchain-groq langchain-huggingface langchain-chroma langgraph langchain-community sentence-transformers chromadb gradio

# 3. VERIFY IMPORTS
import chromadb
from google.colab import userdata
from langchain_groq import ChatGroq
from langchain_huggingface import HuggingFaceEmbeddings

print("✅ ALL TOOLS INSTALLED. You can now run Section 3, 4, 8, and 10 without errors!")

"""---

## 3. Configuration

We define our environment variables here. This acts as the "control center" for our project.
"""

import os
import sys

# 1. AUTO-INSTALL CHECK (Added 'unstructured' for your PDF/Text files)
try:
    from langchain_groq import ChatGroq
    from google.colab import userdata
    import unstructured
except ImportError:
    print("🛠️ Tools missing. Installing the final pieces (takes 45 seconds)...")
    !pip install -qU langchain-groq langchain-chroma langchain-community sentence-transformers chromadb unstructured
    from langchain_groq import ChatGroq
    from google.colab import userdata

# 2. CONFIGURATION
SOURCE_DATA_DIR = "/content/drive/MyDrive/NTU Projects/Mod 5/hr_data"
DRIVE_DB_PATH = "/content/drive/MyDrive/chroma_db"
EMBEDDING_MODEL = "all-mpnet-base-v2"

# 3. SETUP THE BRAIN (Updated to the new Llama 3.3 model)
os.environ["GROQ_API_KEY"] = userdata.get("GROQ_API_KEY")
llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0.3)

print("✅ SUCCESS: Environment is ready. The final pieces are installed!")

"""---

## 4. Provisioning the Knowledge Base

Before our agents can answer questions, they need a library of facts.

*Recall from our previous RAG lesson:* Computers don't read text; they read numbers (vectors). We must "chunk" our documents and embed them into a database.


### The Chunker Lab (Refresher)
Let's quickly verify how our AI "sees" text by testing the chunker on a dummy sentence.
"""

# 🧪 CHUNKER LAB
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Try changing chunk_size to see how it affects the output
my_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=10)
sample_text = "Artificial Intelligence has evolved from simple rule-based systems to complex agentic architectures. In a traditional RAG system, the process is linear: a user asks a question, the system retrieves documents, and the LLM generates an answer. However, this often lacks the reasoning depth required for enterprise tasks."

chunks = my_splitter.create_documents([sample_text])
print(f"📄 Split into {len(chunks)} chunks:")
for i, chunk in enumerate(chunks):
    print(f"[Chunk {i}]: {chunk.page_content}")

"""### The Builder (Ingestion Engine)
Now, let's process your actual files from Google Drive.
"""

# 🏗️ INGESTION ENGINE
from langchain_community.document_loaders import DirectoryLoader, UnstructuredFileLoader
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings

# Initialize Client
persistent_client = chromadb.PersistentClient(path=DRIVE_DB_PATH)
embeddings = HuggingFaceEmbeddings(model_name=EMBEDDING_MODEL)
real_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)

def build_knowledge_base():
    if not os.path.exists(SOURCE_DATA_DIR):
        print(f"❌ Source directory '{SOURCE_DATA_DIR}' not found.")
        return

    print("\n🚀 Starting Ingestion...")
    # This deletes the old, duplicate collections so we start fresh.
    existing_collections = persistent_client.list_collections()
    for col in existing_collections:
        try:
            print(f"   🗑️  Cleaning up old collection: {col.name}")
            persistent_client.delete_collection(col.name)
        except:
            pass

    for item_name in os.listdir(SOURCE_DATA_DIR):
        if item_name.startswith('.'): continue
        file_path = os.path.join(SOURCE_DATA_DIR, item_name)
        safe_name = os.path.splitext(item_name)[0].replace(" ", "_").lower() + "_collection"

        try:
            if os.path.isdir(file_path):
                loader = DirectoryLoader(file_path, glob="**/*", loader_cls=UnstructuredFileLoader)
            else:
                loader = UnstructuredFileLoader(file_path)

            docs = loader.load()
            if not docs: continue

            splits = real_splitter.split_documents(docs)
            Chroma(client=persistent_client, collection_name=safe_name, embedding_function=embeddings).add_documents(splits)
            print(f"   ✅ Indexed: {item_name} -> {safe_name}")
        except Exception as e:
            print(f"   ❌ Error on {item_name}: {e}")

build_knowledge_base()

"""---

## 5. Verification: Test Your Memory

Never trust a black box. Let's force the AI to show us what it found in the database. If this step fails, the agents will have nothing to say.
"""

# 🧐 INSPECTION STATION

try:
    db = Chroma(
        client=persistent_client,
        collection_name="1_collection",
        embedding_function=embeddings
    )
    retriever = db.as_retriever(search_kwargs={"k": 2})

    # Let's ask a question relevant to products, not stores
    query = "What is the last job for Robert"
    results = retriever.invoke(query)

    print(f"\n🔎 Search Results for: '{query}'")
    for doc in results:
        print(f"--- Chunk ---\n{doc.page_content[:150]}...\n")

except Exception as e:
    print(f"⚠️ Error: {e}")

"""---

## 6. The Brain: Building the Router

In a simple RAG system, every query goes to the same place. In an **Agentic System**, we first stop and ask: *"Who is best suited to answer this?"*

### The "Traffic Cop" Pattern
Our Router is a specialized prompt that classifies user intent. It does **not** answer the question; it outputs a **Decision**.

### Why not just one Agent?
* **Accuracy:** A "Shipping Agent" won't accidentally make up facts about "Product Specs."
* **Security:** You can prevent the "Refund Agent" from accessing "User Data."
"""

# 🧠 THE ROUTER NODE
from langchain_core.messages import SystemMessage, HumanMessage

def router_node(state):
    query = state["query"]

    router_prompt = """
    You are a HR Router. Classify the user's query into one of these buckets:

- 'recruitment_agent': Use for CV searches, candidate experience, or hiring suitability.
- 'hr_policy_agent': Use for leave, hybrid work, benefits, and whenever the user says "yes", "sure", or "please" to seeing policies.
- 'tech_interviewer_agent': Use for generating interview questions or screening assessments.
- 'general_agent': Use for greetings or general chat.

Output ONLY the exact key name.
    """

    try:
        response = llm.invoke([SystemMessage(content=router_prompt), HumanMessage(content=query)])
        decision = response.content.strip().lower().strip(".'\"")
    except:
        decision = "general_agent"

    if decision not in ["recruitment_agent", "hr_policy_agent", "tech_interviewer_agent"]:
        decision = "general_agent"

    return {"next_node": decision, "debug_log": f"🚦 Router Decision: {decision}"}

"""### The Router Lab
Let's test the "Brain" in isolation before connecting the body.
"""

# 🧪 ROUTER LAB
test_queries = [
    "Who are the candidates for the senior role?",
    "Evaluate John Tan's interview performance.",
    "How many days of medical leave am I entitled to?",
    "Tell me a joke about robots.",
    "What is the company policy on hybrid work?"
]

print(f"{'QUERY':<30} | {'DECISION':<15}")
print("-" * 50)
for q in test_queries:
    res = router_node({"query": q})
    print(f"{q:<30} | {res['next_node']:<15}")

"""---

## 7. The Specialists: Strict Grounding

Now we build the workers. We use a **Factory Pattern**: a single function `run_grounded_agent` that can act as any specialist depending on the inputs we give it.

**The "Strict Grounding" Rule:** If the retrieved documents are empty, the agent MUST admit ignorance. It is strictly forbidden from using outside knowledge for business facts.
"""



# 🏭 AGENT FACTORY
def run_grounded_agent(state, agent_name, collection_name, persona):
    query = state["query"]

    # 1. Retrieve Data
    try:
        db = Chroma(client=persistent_client, collection_name=collection_name, embedding_function=embeddings)
        docs = db.similarity_search(query, k=10)
        context = "\n\n".join([d.page_content for d in docs])
    except:
        context = ""

    # 2. Strict Check
    if not context.strip():
        return {
            "response": "I could not find that information in our internal documents.",
            "debug_log": state.get('debug_log', '') + f"\n❌ {agent_name}: No context found."
        }

    # 3. Answer with Context
    system_prompt = f"""
    You are the {persona}.
    Answer the user query using ONLY the Context below.
    If the answer is not in the context, say you don't know.

    Context:
    {context}
    """

    response = llm.invoke([SystemMessage(content=system_prompt), HumanMessage(content=query)])

    return {
        "response": response.content,
        "debug_log": state.get('debug_log', '') + f"\n✅ {agent_name}: Used {len(docs)} docs."
    }

# Define the actual nodes
def recruitment_agent_node(state):
    return run_grounded_agent(state, "Recruitment Agent", "1_collection", "Senior Recruitment Specialist")

def hr_policy_agent_node(state):
    query = state["query"].lower().strip()
    # If user says 'yes', we force a search for the policy summary
    search_query = "What are the company HR benefits, leave policies, and hybrid work models?" if query in ["yes", "sure", "ok"] else state["query"]

    return run_grounded_agent(state, "HR Policy Agent", "3_collection", f"HR Policy Expert. Provide details on: {search_query}")


def tech_interviewer_agent_node(state):
    # 🧠 THE ULTIMATE FIX: We tell the search to specifically find all three files
    # so the AI has the full 'menu' of questions ready in its hand.
    search_query = "Interview questions for Linda Quek HR, David Chen Software, Sarah Lim Logistics"

    persona = (
        "Technical Interviewer. You are an expert at identifying the correct candidate from history. "
        "STEP 1: Look at the very last message in the chat. "
        "If the name 'Linda' or 'HR' was mentioned, you MUST provide the HR Director questions. "
        "If 'David' or 'Software' was mentioned, provide the Software Architect questions. "
        "If 'Sarah' or 'Logistics' was mentioned, provide the Logistics questions. "
        "Provide exactly 3 questions. Do not mention Sarah Lim if the user just asked for an HR CV. "
        "Finish by asking if they want to see HR benefits or policies."
    )

    return run_grounded_agent(state, "Tech Interviewer Agent", "2_collection", f"{persona} Search: {search_query}")


def general_agent_node(state):
    # General agent is allowed to chat freely
    res = llm.invoke([SystemMessage(content="You are a helpful assistant."), HumanMessage(content=state["query"])])
    return {
        "response": res.content,
        "debug_log": state.get('debug_log', '') + "\n💬 General Agent: Chatting freely."
    }

"""---

## 8. Orchestration: LangGraph

We have the Brain (Router) and the Body (Agents). Now we use **LangGraph** to wire them together into a state machine.
"""

# 🕸️ BUILDING THE GRAPH
from typing import TypedDict, List
from langchain_core.messages import BaseMessage
from langgraph.graph import StateGraph, END

class AgentState(TypedDict):
    query: str
    response: str
    next_node: str
    debug_log: str

# Initialize Graph
workflow = StateGraph(AgentState)

# Add Nodes
workflow.add_node("router", router_node)
workflow.add_node("recruitment_agent", recruitment_agent_node)
workflow.add_node("hr_policy_agent", hr_policy_agent_node)
workflow.add_node("tech_interviewer_agent", tech_interviewer_agent_node)
workflow.add_node("general_agent", general_agent_node)

# Add Edges (The Wiring)
workflow.set_entry_point("router")
workflow.add_conditional_edges(
    "router",
    lambda state: state["next_node"] # The function that decides where to go
)
workflow.add_edge("recruitment_agent", END)
workflow.add_edge("hr_policy_agent", END)
workflow.add_edge("tech_interviewer_agent", END)
workflow.add_edge("general_agent", END)

# Compile
app = workflow.compile()
print("✅ Agentic Graph Compiled.")

"""---

## 9. Testing the System

Let's run a full simulation in the console.
"""

# 🕵️ SIMULATION
def test_agent(question):
    print(f"\n❓ Asking: {question}")
    result = app.invoke({"query": question})
    print(f"🤖 Answer: {result['response'].strip()}")
    print(f"🧠 Log: {result['debug_log']}")
    print("-" * 40)

# Test 1: Candidate Search
test_agent("Find a candidate with HR experience.")

# Test 2: Interview Questions
test_agent("What are 3 interview questions for Linda?")

# Test 3: HR Policy
test_agent("What is our policy on hybrid work?")

"""---

## 10. The User Interface (Gradio)

Finally, we wrap our system in a "Transparent UI." This allows users to chat normally, but also peek behind the curtain to see the **Thinking Process** (the `debug_log`).
"""

# 10. THE USER INTERFACE
import gradio as gr
import datetime
import pytz # <--- We add this to fix the timezone

# Determine the greeting based on Singapore time
sg_timezone = pytz.timezone('Asia/Singapore')
now_sg = datetime.datetime.now(sg_timezone)
hour = now_sg.hour

if hour < 12:
    greeting = "Good morning! ☀️"
elif 12 <= hour < 18:
    greeting = "Good afternoon! ☕"
else:
    greeting = "Good evening! 🌙"

# The rest of your welcome_msg code follows...

# Final refined welcome message
welcome_msg = f"{greeting}\n\nI am the Little Lotus HR Assistant. I am ready to help you with:\n\n" \
              f"• **Candidate Profiles:** Deep dives into our **Software**, **Logistics**, and **HR** applicants.\n\n" \
              f"• **Interview Prep:** I can suggest tailored questions for your next candidate interview.\n\n" \
              f"• **HR Policy Guidance:** Instant answers regarding our company **HR benefits**." \
              f"\n\nHow can I assist your recruitment process today?"

def chat_interface(message, history):
    try:
        result = app.invoke({"query": message})
        answer = result.get("response", "No response.")
        log = result.get("debug_log", "No log.")

        # Format output with a collapsible "Thinking" section
        display_text = f"{answer}\n\n<details><summary>🧠 <b>Thinking Process</b></summary>\n<pre>{log}</pre>\n</details>"
        return display_text
    except Exception as e:
        return f"Error: {str(e)}"

demo = gr.ChatInterface(
    fn=chat_interface,
    title="🌸 Little Lotus Recruitment Assistant",
    description="Ask me about our candidates or request their CV links.",
    # This is the updated format that fixes the error:
    chatbot=gr.Chatbot(value=[{"role": "assistant", "content": welcome_msg}]),
)

demo.launch(debug=True)

"""---

## 11. Debugging & Troubleshooting

If your agent fails, check these common issues:

| Symptom | Probable Cause | Fix |
| :--- | :--- | :--- |
| **"I could not find that..."** | Ingestion failed or file missing. | Check Section 5. Does the file exist in Drive? |
| **Router picks wrong agent** | Router prompt is ambiguous. | Edit `router_node` prompt definitions. |
| **Gradio Error** | State mismatch. | Ensure `AgentState` keys match what your nodes return. |

---

## 12. Extensions

How can you take this further?
1.  **Memory:** Add `history` to the `AgentState` so the bot remembers "it" refers to the iPhone you just mentioned.
2.  **Tools:** Give the Product Agent a calculator tool to sum up prices.
3.  **Guards:** Add a "Profanity Filter" node before the Router.

---

## 13. Summary

Today we built a system that **thinks before it speaks**.
* We replaced a single LLM with a **Graph of Agents**.
* We implemented **Semantic Routing** to direct traffic.
* We enforced **Strict Grounding** to prevent hallucinations.

This architecture is the foundation of modern Enterprise AI.
"""
